# Generated by Django 4.0.6 on 2022-07-20 17:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart_url', models.URLField(blank=True, default='')),
                ('key', models.CharField(blank=True, default='', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('original_artist', models.CharField(blank=True, default='', max_length=300)),
                ('tempo', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=300)),
                ('video_url', models.URLField(blank=True, default='')),
                ('tags', models.ManyToManyField(blank=True, related_name='songs', to='bandapp.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Setlist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('title', models.CharField(max_length=300)),
                ('songs', models.ManyToManyField(blank=True, related_name='setlists', to='bandapp.song')),
                ('tags', models.ManyToManyField(blank=True, related_name='setlists', to='bandapp.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=300)),
                ('setlist', models.ManyToManyField(blank=True, to='bandapp.setlist')),
                ('tags', models.ManyToManyField(blank=True, related_name='gigs', to='bandapp.tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Band',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandcamp', models.CharField(blank=True, default='', max_length=300)),
                ('description', models.TextField(blank=True)),
                ('facebook', models.CharField(blank=True, default='', max_length=300)),
                ('instagram', models.CharField(blank=True, default='', max_length=300)),
                ('location', models.CharField(blank=True, default='', max_length=300)),
                ('name', models.CharField(max_length=300)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('soundcloud', models.CharField(blank=True, default='', max_length=300)),
                ('twitter', models.CharField(blank=True, default='', max_length=300)),
                ('youtube', models.CharField(blank=True, default='', max_length=300)),
                ('tags', models.ManyToManyField(blank=True, related_name='bands', to='bandapp.tag')),
            ],
        ),
    ]
