# Generated by Django 4.0.6 on 2022-07-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setlist',
            name='songs',
            field=models.ManyToManyField(blank=True, to='bandapp.song'),
        ),
        migrations.AlterField(
            model_name='song',
            name='key',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='original_artist',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='song',
            name='tempo',
            field=models.IntegerField(blank=True),
        ),
    ]
