# Generated by Django 4.0.6 on 2022-07-19 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandapp', '0002_alter_setlist_songs_alter_song_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='key',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='original_artist',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='song',
            name='tempo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
