# Generated by Django 4.0.6 on 2022-07-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bandapp', '0002_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(blank=True, choices=[('red', 'red'), ('orange', 'orange'), ('yellow', 'yellow'), ('olive', 'olive'), ('green', 'green'), ('teal', 'teal'), ('blue', 'blue'), ('violet', 'violet'), ('purple', 'purple'), ('pink', 'pink'), ('brown', 'brown'), ('grey', 'grey'), ('black', 'black')], default='blue', max_length=6),
        ),
    ]
