# Generated by Django 4.0.6 on 2022-07-20 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandapp', '0003_alter_tag_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='color',
            new_name='colour',
        ),
    ]
