# Generated by Django 4.0.6 on 2022-07-20 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bandapp', '0005_tag_rename_date_created_setlist_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='group',
        ),
    ]
